=== pl2-game/pl2script/v01/pl2script/data/simple/common/Class.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Class" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Class">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="class_id " primary="yes" unique="yes" clustered="no" order="asc"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="class_id" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="tag" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="class_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="local" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="savable" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== pl2-game/pl2script/v01/pl2script/data/simple/common_old/Class.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Class.xsd" generated="2014-04-18T09:07:53">
<Class>
<class_id>1</class_id>
<tag>class_Script</tag>
<class_name>Script</class_name>
<local>Сценарий</local>
<savable>0</savable>
</Class>
<Class>
<class_id>2</class_id>
<tag>class_Learner</tag>
<class_name>Learner</class_name>
<local>Обучающийся</local>
<savable>1</savable>
</Class>
<Class>
<class_id>3</class_id>
<tag>class_Scene</tag>
<class_name>Scene</class_name>
<local>Сцена</local>
<savable>1</savable>
</Class>
<Class>
<class_id>4</class_id>
<tag>class_Path</tag>
<class_name>Path</class_name>
<local>Путь</local>
<savable>1</savable>
</Class>
<Class>
<class_id>5</class_id>
<tag>class_Bag</tag>
<class_name>Bag</class_name>
<local>Сумка</local>
<savable>1</savable>
</Class>
<Class>
<class_id>6</class_id>
<tag>class_Product</tag>
<class_name>Product</class_name>
<local>Предмет</local>
<savable>1</savable>
</Class>
<Class>
<class_id>7</class_id>
<tag>class_Dialog</tag>
<class_name>Dialog</class_name>
<local>Диалог</local>
<savable>0</savable>
</Class>
<Class>
<class_id>8</class_id>
<tag>class_Prompt</tag>
<class_name>Prompt</class_name>
<local>Вариант</local>
<savable>0</savable>
</Class>
<Class>
<class_id>9</class_id>
<tag>class_Fact</tag>
<class_name>Fact</class_name>
<local>Факт</local>
<savable>0</savable>
</Class>
<Class>
<class_id>10</class_id>
<tag>class_Answer</tag>
<class_name>Answer</class_name>
<local>Ответ</local>
<savable>0</savable>
</Class>
</dataroot>
