=== pl2-game/pl2script/v01/pl2script/data/simple/common_old/Schema_meta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Schema_meta" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Schema_meta">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Table_Name Field_name " primary="yes" unique="yes" clustered="no" order="asc asc"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Table_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Field_Pos" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Field_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Field_Type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Field_Len" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Field_Dec" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Field_Type_Paradox" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="comment" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="look_table" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="look_field" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="disp_field" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="auto_incriment" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="Динамичность" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Область_x0020_возможных_x0020_значений" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Caption" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Header" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Ключ" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="look_schema" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== pl2-game/pl2script/v01/pl2script/data/simple/common_old/Schema_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Schema_meta.xsd" generated="2014-04-18T10:05:20">
<Schema_meta>
<Table_Name>Schema_list</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelLevel</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhase</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhaseLevel</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>Models</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>T</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<comment></comment>
<auto_incriment>0</auto_incriment>
<Caption></Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>-</Table_Name>
<Field_Pos>0</Field_Pos>
<Field_name>-</Field_name>
<Field_Type>B</Field_Type>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<auto_incriment>0</auto_incriment>
<look_schema>MODEL</look_schema>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_list</Table_Name>
<Field_Pos>1</Field_Pos>
<Field_name>schema_name</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_list</Table_Name>
<Field_Pos>2</Field_Pos>
<Field_name>schema_path</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>1</Field_Pos>
<Field_name>Table_Name</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>2</Field_Pos>
<Field_name>Field_Pos</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>3</Field_Pos>
<Field_name>Field_name</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>4</Field_Pos>
<Field_name>Field_Type</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>5</Field_Pos>
<Field_name>Field_Len</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>6</Field_Pos>
<Field_name>Field_Dec</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>7</Field_Pos>
<Field_name>Field_Type_Paradox</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>8</Field_Pos>
<Field_name>Comment</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>9</Field_Pos>
<Field_name>Look_Table</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<look_table>Schema_list</look_table>
<look_field>Table_Name</look_field>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>10</Field_Pos>
<Field_name>Look_Field</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<look_table>Schema_list</look_table>
<look_field>Field_name</look_field>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>11</Field_Pos>
<Field_name>Disp_Field</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<look_table>Schema_list</look_table>
<look_field>Field_name</look_field>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>12</Field_Pos>
<Field_name>auto_incriment</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>1</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>13</Field_Pos>
<Field_name>Динамичность</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>14</Field_Pos>
<Field_name>Область возможных значений</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>15</Field_Pos>
<Field_name>Caption</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>16</Field_Pos>
<Field_name>Header</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>17</Field_Pos>
<Field_name>Ключ</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>Schema_meta</Table_Name>
<Field_Pos>255</Field_Pos>
<Field_name>Look_Base</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<auto_incriment>0</auto_incriment>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelLevel</Table_Name>
<Field_Pos>1</Field_Pos>
<Field_name>LevelId</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<comment>Уровень</comment>
<auto_incriment>0</auto_incriment>
<Caption>Уровень</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelLevel</Table_Name>
<Field_Pos>2</Field_Pos>
<Field_name>LevelName</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<comment>Навзвание уровня</comment>
<auto_incriment>0</auto_incriment>
<Caption>Навзвание уровня</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelLevel</Table_Name>
<Field_Pos>3</Field_Pos>
<Field_name>LevelAbstractionRating</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<comment>Значение абстрагирования</comment>
<auto_incriment>0</auto_incriment>
<Caption>Значение абстрагирования</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhase</Table_Name>
<Field_Pos>1</Field_Pos>
<Field_name>PhaseId</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<comment>Фаза</comment>
<auto_incriment>0</auto_incriment>
<Caption>Фаза</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhase</Table_Name>
<Field_Pos>2</Field_Pos>
<Field_name>PhaseName</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<comment>Название фазы</comment>
<auto_incriment>0</auto_incriment>
<Caption>Название фазы</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhase</Table_Name>
<Field_Pos>3</Field_Pos>
<Field_name>DemingName</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>10</Field_Type_Paradox>
<comment>Название по циклу Деминга</comment>
<auto_incriment>0</auto_incriment>
<Caption>Название по циклу Деминга</Caption>
</Schema_meta>
<Schema_meta>
<Table_Name>ModelPhase</Table_Name>
<Field_Pos>4</Field_Pos>
<Field_name>PhaseRate</Field_name>
<Field_Len>0</Field_Len>
<Field_Dec>0</Field_Dec>
<Field_Type_Paradox>4</Field_Type_Paradox>
<comment>Значение фазы рациональности</comment>
